# For available configuration options, see:
#   https://github.com/standardrb/standard
ruby_version: 3.0
#fix: true               # default: false
parallel: true          # default: false
format: progress        # default: Standard::Formatter
extend_config:
  - .buddylint.yml
ignore:
  - 'whisper.cpp/**/*'
